tasks:
  - before: >
      echo | ssh-keygen -t rsa -C "keyne.cleetus@revature.com" -q -N "" &&
      chmod 644 ~/.ssh/id_rsa.pub &&
      chmod 600 ~/.ssh/id_rsa &&
      ssh-keyscan github.com >> ~/.ssh/known_hosts
  - init: git remote set-url origin git@github.com:keynecleetus/TestingGitUsingSSH.git

           
